name: Daily Update

on:
  schedule:
    - cron: "3 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aborruso/andy-image:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      - name: Ensure data directory exists
        run: mkdir -p data

      - name: Run full_dump.js
        run: cd scripts && node full_dump.js

      - name: Run lista.sh
        run: |
          cd scripts && bash lista.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Update data" || echo "No changes to commit"
          git push
